addons/rmsmartshape/documentation/Controls.md, addons/rmsmartshape/plugin.gd
- Control Points render on top of verts
- Control Points take priority over verts
- Control points and verts take priority over creating a point on an edge
- Unless ALT is held down
- Documentation Updated
=> Set cp priority, update render method, update controls, update docs

addons/rmsmartshape/plugin.gd, addons/rmsmartshape/shapes/shape_base.gd, addons/rmsmartshape/strings.gd
This one is super useful for me. When working with SmartShape2D I often have to create a copy of the same shape but without all the points. Now with holding down ALT+CTRL it will do just that, and add the first point where you clicked, and sets the mode to the create-vertex-mode. I also added a shortcut (ESC/ENTER) to switch from the create-vert-mode to edit-vert-mode. Together it feels very nice for me to work with now and it shouldn't mess anything up for less experienced users.
The reason I chose ALT+CTRL instead of ALT+SHIFT is because I think that should be reserved for adding a new vertex between the closest line to the mouse
=> A shortcut to copy the shape with a new point

addons/rmsmartshape/assets/icon_editor_handle_selected.svg, addons/rmsmartshape/assets/icon_editor_handle_selected.svg.import, addons/rmsmartshape/plugin-functionality.gd, addons/rmsmartshape/plugin.gd
- holding down CTRL highlights the closest point to your mouse, you can then start dragging it, remove it or change it's curve just as if your mouse was on the point. Makes editing a shape way less tedious, quicker and more fun
- holding down ALT makes a new point between the closest edge rather than the end of the shape. The old behavior is still present in the add point tool, which makes sense because that create point tool is really for drawing the initial shape and the edit tool is for editing that shape without having to care of where you started/finished drawing it.
- minor change: made the second preview line when using create vertex tool thinner, this helps to know between where the next point will be created. Also makes it more obvious that you shouldn't draw shapes CCW because …
=> Closest point select

addons/rmsmartshape/assets/Anchor.svg
Change the Anchor.svg color to blue, because new users might think that it's a Control node when it's green.
From:
To:
This is my first ever pull request, let me know if I did anything wrong.
=> Change Anchor.svg color to blue

addons/rmsmartshape/plugin.gd
The legacy toolbar got added every time you enable the plugin, but it never got removed when the plugin was disabled. This commit makes sure the the legacy toolbar is removed when the plugin is disabled.
=> Fix legacy toolbar reinsertion on plugin re-enable

addons/rmsmartshape/plugin.gd
The code in `_process` does not need to be handled every frame, but only on certain events.
This reduces the editor CPU usage quite a bit.
I didn't analyze the whole code base, so if there's actually some special edge case where this doesn't work, let me know.
=> Reduce CPU usage by removing _process from editor plugin

addons/rmsmartshape/materials/edge_material.gd, addons/rmsmartshape/shapes/shape_base.gd
Hi,
This small edit adds a checkbox "randomize_texture" in the Edge Material.
If this bool is true, instead of choosing the texture from the point property, SS2D will randomize the choice of texture inside the textures array.
atn
=> randomize texture choice in edge material

addons/rmsmartshape/shapes/shape_base.gd
Hi, the last pull introduced a bug (can no more choose the idx texture for a vertex) that is corrected in this PR.
I am a bit ashamed to have forgotten this var association:
"texture_idx = "
It should work a bit better now ... 
sorry about that,
atn
=> bug correction on vertex index

addons/rmsmartshape/plugin.gd
When hovering over a vertex in vertex-edit-mode, a popup is shown to display information about this vertex.
I always found this popup very obstructive as it hides exactly that part of the screen I'm currently editing.
This patch offsets the info panel slightly downwards, so it still feels connected to the vertex, but does not occlude the edited area.
Before:
After:
=> Slightly offset vertex info panel to be less obstructive

addons/rmsmartshape/shapes/shape_anchor.gd
Currently, anchors explicitly reset the target nodepath when _exit_tree is triggered. 
This would occur for example when switching scene tabs and is very annoying to work with.
This patch removes this behavior.
=> Fix anchors resetting shape path on _exit_tree

addons/rmsmartshape/materials/shape_material.gd, addons/rmsmartshape/shapes/mesh.gd, addons/rmsmartshape/shapes/shape_closed.gd, addons/rmsmartshape/shapes/shape_render.gd
Exposes the "show behind parent" property for fill textures.
This is useful when having multiple smart shapes that overlap each other.
The following screenshot shows what usually happens:  the edges of the underlying shape overlap the fill mesh of the shape above.
With this patch, you can set the following properties in the shape material to get a better overlapping behavior that always works without fiddling with z-indexes.
```
Fill Texture Show Behind Parent = true
Fill Texture Z Index = 0
```
=> Add "Show behind parent" option for fill textures

addons/rmsmartshape/actions/action_add_point.gd, addons/rmsmartshape/actions/action_delete_point.gd, addons/rmsmartshape/actions/action_split_curve.gd, addons/rmsmartshape/plugin.gd, addons/rmsmartshape/shapes/shape_base.gd, addons/rmsmartshape/strings.gd
This PR implements deferred mesh updates to improve performance and UX with big shapes:
Deferred updates are turned off by default and can be turned on in the toolbar:
Setting of deferred updates is persisted in a config file along with snapping settings.
Additionally:
1. Removes unneeded "_process" calls, excessive draws and shape mesh updates.
2. Turns off setting render node owners. It seems to slow down editor as things stand with Godot 4.0. The purpose of that function still remains unclear and things seem to work fine without it.
All the tests pass.
While under review, my PRs (#118, #123 and #126) are available merged in this branch: https://github.com/limbonaut/SmartShape2D/tree/integration
=> Improve UX and performance with deferred updates and small optimisations

addons/rmsmartshape/actions/action_add_collision_nodes.gd, addons/rmsmartshape/actions/action_set_pivot.gd, addons/rmsmartshape/plugin.gd, addons/rmsmartshape/shapes/shape_base.gd, addons/rmsmartshape/shapes/shape_closed.gd
This is a set of patches that try to improve the performance and reduce some code duplication.
546645a77fceac2ac45e8079824a76e961195fb7 alone reduces overall generation time by 30-40%. See also #119.
There is still a lot more to optimize, but it's a start.
Depending on the state of #118, I can rebase my branch on @narren96c's branch.
All tests pass of course.
=> Performance improvements and refactoring

addons/rmsmartshape/editors/action_property_inspector_plugin.gd, addons/rmsmartshape/editors/normal_range_inspector_plugin.gd, addons/rmsmartshape/plugin.gd, project.godot
Fixes issues with `_parse_property` signature in Godot 4.1 while preserving backwards compatibility.
Also fixes lack of theming in "Make Unique" dialog.
<details>
<summary>Error messages that this PR fixes</summary>
```
res://addons/rmsmartshape/editors/action_property_inspector_plugin.gd:41 - Parse Error: The function signature doesn't match the parent. Parent signature is "_parse_property(Object, Variant.Type, String, PropertyHint, String, int, bool) -> bool".
res://addons/rmsmartshape/editors/normal_range_inspector_plugin.gd:32 - Parse Error: The function signature doesn't match the parent. Parent signature is "_parse_property(Object, Variant.Type, String, PropertyHint, String, int, bool) -> bool".
```
</details>
While under review, my PRs (#118, #123 and #126) are available merged in …
=> Fix Godot 4.1 errors

addons/rmsmartshape/documentation/Shapes.md
Currently `fill_texture_z_index` defaults to `-10` which can be confusing (it was to me) to new users when layering with other Godot nodes as the z-sorting appears random at first.
This PR adds information why the behaviour is there and how to deal with it.
=> Added documentation for fill_texture_z_index

addons/rmsmartshape/actions/action_add_collision_nodes.gd, addons/rmsmartshape/actions/action_add_point.gd, addons/rmsmartshape/actions/action_close_shape.gd, addons/rmsmartshape/actions/action_cut_edge.gd, addons/rmsmartshape/actions/action_delete_control_point.gd, addons/rmsmartshape/actions/action_delete_point.gd, addons/rmsmartshape/actions/action_delete_points.gd, addons/rmsmartshape/actions/action_invert_orientation.gd, addons/rmsmartshape/actions/action_make_shape_unique.gd, addons/rmsmartshape/actions/action_move_control_points.gd, addons/rmsmartshape/actions/action_move_verticies.gd, addons/rmsmartshape/actions/action_open_shape.gd, addons/rmsmartshape/actions/action_set_pivot.gd, addons/rmsmartshape/actions/action_split_curve.gd, addons/rmsmartshape/actions/action_split_shape.gd, addons/rmsmartshape/editors/action_property_inspector_plugin.gd, addons/rmsmartshape/plugin.gd, addons/rmsmartshape/plugin_functionality.gd, addons/rmsmartshape/shapes/point_array.gd, addons/rmsmartshape/shapes/shape.gd, addons/rmsmartshape/shapes/shape_anchor.gd, addons/rmsmartshape/shapes/shape_base.gd, addons/rmsmartshape/shapes/shape_closed.gd, addons/rmsmartshape/shapes/shape_open.gd, addons/rmsmartshape/strings.gd, project.godot, tests/unit/test_anchor.gd, tests/unit/test_plugin_actions.gd, tests/unit/test_shape_base.gd, tests/unit/test_shape_open.gd
This PR aims to improve user experience when creating shapes as discussed in #117 and #101.
The `SS2D_Shape` node combines the functionality of open and closed shapes. A shape can be closed at any time by adding a point on top of the first point. Additionally, the new Cut Edge tool allows for opening shapes and can also split a shape into two smaller shapes (#101). Furthermore, the update includes the ability to create points with Bezier curves directly while adding them. The added functionality is fully compatible with the editor's undo-redo system.
`SS2D_Shape_Open` and `SS2D_Shape_Closed` are marked as deprecated and inherit from `SS2D_Shape`. These
classes are empty now and do not provide any additional functionality. They are needed for backwards compatibility. However, they can be …
=> Improve UX when creating open and closed shapes

.gitignore, addons/rmsmartshape/materials/shape_material.gd, addons/rmsmartshape/shapes/shape.gd
- **Scaling:** Useful when working with non-pixelart based assets
- **Global alignment** (position and rotation): Useful when shapes should overlap and the tiling should continue seamlessly
- **Offsets** (position and rotation): Works _without_ global alignments but especially handy there for fine-tuning
- (And: Added Mac .DS_Store files to gitignore)
https://github.com/SirRamEsq/SmartShape2D/assets/7897006/d65feeea-adea-4bf4-9206-2d18cc658b66
I ran the GUT-tests successfully. But I have never written tests in Godot so I didn't add new ones.
<details>
<summary>Show log</summary>
```
res://tests/unit/test_tuple.gd.
* test_equality
* test_find
* test_get_other_value
* test_is_tuple
23/23 passed.
==============================================
= Run Summary …
```
=> Additional fill texture options

addons/rmsmartshape/actions/action_set_pivot.gd, addons/rmsmartshape/assets/icon_editor_handle.svg.import, addons/rmsmartshape/assets/icon_editor_handle_add.svg.import, addons/rmsmartshape/assets/icon_editor_handle_bezier.svg.import, addons/rmsmartshape/assets/icon_editor_handle_control.svg.import, addons/rmsmartshape/assets/icon_editor_handle_selected.svg.import, addons/rmsmartshape/plugin.gd, addons/rmsmartshape/shapes/shape.gd, tests/unit/test_plugin_actions.gd
- Adjusted mouse delta while editing vertices and control points on shapes where global_transform != identity
- "Set Pivot" action now works as expected on shapes where global_transform != identity
- Fixed a small issue where the editor buttons do not disappear after a shape is deselected
- Test change: `ActionSetPivot` action no longer takes a Transform2D argument
=> Improved editing for transformed shapes (again)

.gitattributes, README.md
=> Only include the "addons/rmsmartshape" when downloading from the Asset Library

addons/rmsmartshape/shapes/shape.gd
Closes #141 
Apparently the problem was simply that the wrong inverse method was being used. `inverse()` instead of `affine_inverse()`.
[As per the documentation](https://docs.godotengine.org/en/stable/classes/class_transform2d.html#class-transform2d-method-inverse):
> [Transform2D](https://docs.godotengine.org/en/stable/classes/class_transform2d.html#class-transform2d) inverse ( ) const
Returns the inverse of the transform, under the assumption that the transformation basis is orthonormal (i.e. rotation/reflection is fine, scaling/skew is not). Use [affine_inverse](https://docs.godotengine.org/en/stable/classes/class_transform2d.html#class-transform2d-method-affine-inverse) for non-orthonormal transforms (e.g. with scaling).
With this, the transform of the polygon itself is ignored, and …
=> Use correct inverse when applying transform of SS2D shape on collision polygon

addons/rmsmartshape/plugin.gd, addons/rmsmartshape/shapes/shape.gd
When using create tool and holding ALT key, points should be inserted at the closest edge.
Spotted by @mphe, and reported on Discord.
=> Fix create tool alt mode not working

addons/rmsmartshape/actions/action_delete_point.gd, addons/rmsmartshape/actions/action_delete_points.gd, addons/rmsmartshape/actions/action_move_control_points.gd, addons/rmsmartshape/actions/action_move_verticies.gd, addons/rmsmartshape/actions/action_split_shape.gd, addons/rmsmartshape/lib/tuple.gd, addons/rmsmartshape/plugin.gd, addons/rmsmartshape/plugin_functionality.gd, addons/rmsmartshape/scenes/GUI_Edge_InfoPanel.gd, addons/rmsmartshape/shapes/index_map.gd, addons/rmsmartshape/shapes/point_array.gd, addons/rmsmartshape/shapes/shape.gd, tests/unit/test_edge.gd, tests/unit/test_index_map.gd, tests/unit/test_point_array.gd, tests/unit/test_shape_base.gd, tests/unit/test_shape_open.gd, tests/unit/test_tuple.gd
Some code operates on two arbitrary points, e.g. for constraint handling in PointArray. These point tuples have been represented as Array[int] so far.
This PR replaces these usages of Array[int] with Vector2i for several reasons:
- Less error prone
- No more problems with typed arrays
- Better suits the tuple type: there are exactly two int elements, not more, not less, nothing else.
`tuple.gd` contains utility functions for dealing with said index tuples as they have the special equality behavior `T(x, y) <=> T(y, x)`, which needs to be respected when searching in arrays or dictionaries using this tuple type.
Unfortunately, Godot does not allow custom equality and hash functions, so we have to write our own accessor functions for arrays and dictionaries.
This patch improves the previous …
=> Refactor index-tuple implementation

addons/rmsmartshape/shapes/shape.gd
- Distortions appear because we rely on normals in the process of building the quad.
- Reworks algorithm to rely on delta vectors instead.
- Aligns better with overall shape geometry, and also improves results of `render_offset`.
=> Optimize corner quad generation

addons/rmsmartshape/documentation/Shapes.md, addons/rmsmartshape/shapes/point_array.gd, addons/rmsmartshape/shapes/shape.gd, test_large_curvy.tscn, tests/unit/test_shape_open.gd
The time needed to generate collision shapes depends on two factors: edge generation and the convex decomposition of the polygon by `CollisionPolygon2D`.
Especially the latter is very expensive on large shapes that are difficult to decompose.
Additionally the amount of points the collision polygon consists of depends on the tesselation settings.
This patch tweaks the default tesselation settings to provide pretty much the same visual quality at less computation time.
I think they can be even lowered more to `tesselation_tolerance = 7.0` and maybe `tesselation_stages = 3`. 
I think it's better to provide faster defaults and let users increase them if necessary. Need feedback on this.
This also speeds up regular edge generation respectively.
Edit: Settled on `tesselation_stages = 3` but …
=> Optimize collision generation performance

addons/rmsmartshape/shapes/shape.gd
=> Don't use `CollisionGenerationMethod.Fast` in open shapes

addons/rmsmartshape/shapes/shape.gd
Fix invisible edges issue for web export by processing index maps sequentially to avoid threading issues (while it is probably slower than using thread).
Before:
(The edges (grass) is missing)
After:
=> Fixing Invisible Edges for Web Export

addons/rmsmartshape/shapes/shape.gd
I believe the issue originates from SmartShape2D rather than Rapier2D, due to the way collision data is generated. While there is no apparent problem when using the default Godot physics engine, it is inconsistent that the Fast collision generation method produces a duplicated vertex, whereas the Precise method does not.
For the implementation, a straightforward fix would be to exclude the last vertex directly in shape.gd:
```py
func _generate_collision_points_fast() -> PackedVector2Array:
var tessellated_points: PackedVector2Array = _points.get_tessellated_points()
return tessellated_points.slice(0, tessellated_points.size() - 1)
```
However, since point_array.gd already caches distinct points, I opted for the approach that avoids reallocating a PackedVector2Array each time the getter is …
=> Add distinct tesselated vertices cache for fast collision

addons/rmsmartshape/actions/action_add_collision_nodes.gd, addons/rmsmartshape/collision_gen.gd, addons/rmsmartshape/collision_gen.gd.uid, addons/rmsmartshape/plugin.gd, addons/rmsmartshape/shapes/shape.gd, addons/rmsmartshape/strings.gd, addons/rmsmartshape/tools/collision_tool.gd, addons/rmsmartshape/tools/collision_tool.gd.uid, addons/rmsmartshape/tools/editor_tool.gd, addons/rmsmartshape/tools/editor_tool.gd.uid, examples/collisions.tscn, tests/unit/test_collisions.gd, tests/unit/test_collisions.gd.uid, tests/unit/test_plugin_actions.gd
This started out with a small idea to use `Geometry2D.offset_polyline()` to generate collisions for open shapes.
But then edge cases and the feature creep appeared and it grew into something much larger :D 
This PR improves collision generation and makes the old mesh based approach pretty much obsolete.
It adds faster collision generation for open shapes and introduces hollow collision generation for closed shapes, which solves #110.
`collision_offset` and `collision_size` will now be correctly applied as well.
The performance improvement is around 6x faster (0.05ms vs 0.3 ms on a rather simple test scene) than the old mesh based approach.
I also added a `collisions.tscn` example that demonstrates the different collision methods on closed and open shapes.
I also reworked the Collision …
=> Collision generation and workflow improvements
